### ISSUE TITLE
全部复制 Cookie 这个 Header的步骤有问题

### ISSUE THREAD

**Issue by cabalistljt** [YukiCoco/CheapSteam#1]
我的steamcookie是这样的
cookie: 
timezoneOffset=XXXXXXX; _ga=GAXXXXXXX; steamMachineAuthXXXXXXXXXXXXXXXX=XXXXXXXXXXXXXXXXXXXXXXXXX; steamRememberLogin=XXXXXXXXXXXXXXXXXXXXXXXXXXXX; browserid=XXXXXXXXXXXXXXXXXXX; sessionid=XXXXXXXXXXXXXXXXXXXXXXXXXXXX; steamLoginSecure=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; webTradeEligibility=XXXXXXXXallowedXXXXXXXXXXallowed_at_timeXXXXXXXXXXXsteamguard_required_daysXXXXXXXXXXnew_device_cooldown_daysXXXXXXXXtime_checkedXXXXXXXXXXX

cookie那一段不是很清楚复制哪一段

**Comment by YukiCoco** [comment]
全部复制就可以

**Comment by cabalistljt** [comment]
全部复制我打开exe闪退,是哪里不对么

**Comment by cabalistljt** [comment]
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ChpStmScraper.Program.<>c__DisplayClass13_1.<Start>b__2(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

程序运行出现这些字样然后就关闭了

**Comment by shui670** [comment]
一样的问题，出现上诉字样后停止工作

**Comment by YukiCoco** [comment]
换一下 buff session

**Comment by shui670** [comment]
> 换一下 buff session

感谢，buff不能直接双击复制，会不完整，显示框显示的也不完整，需要手动拉到左边后从头到尾复制

**Comment by cabalistljt** [comment]
> > 换一下 buff session
> 
> 感谢，buff不能直接双击复制，会不完整，显示框显示的也不完整，需要手动拉到左边后从头到尾复制

感谢,我就是这一步出错了
