### ISSUE TITLE
win 环境下在连接steam可用性后直接退出。

### ISSUE THREAD

**Issue by Red5Timor** [YukiCoco/CheapSteam#20]
![image](https://user-images.githubusercontent.com/71250706/151116111-59957c4d-7f63-4a95-af58-4d4338dad1ff.png)

**Comment by Red5Timor** [comment]
环境是win11 专业版

**Comment by YukiCoco** [comment]
确定你正确好配置代理或使用 [社区重定向工具](https://keylol.com/t339527-1-1)，连接失败后直接闪退的问题将在这几天修复。
